language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-udemy npm run test 
    
deploy: 
  provider: elastickbeanstalk
  region: "us-east-1"
  app: "Dockerreactudemy" 
  env: "Dockerreactudemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-994527103245"
  bucket_path: "Dockerreactudemy"
  on:
    branch: master 
      
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY